# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_portfolio_current_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('stock_symbol', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('per_share_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='users',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='current_value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
